### ISSUE TITLE
zip logを実行すると「ログがありません。」と表示される

### ISSUE THREAD

**Issue by ghost** [takahiro-eno/Telnetman2#3]
Telnetmanをありがたく使わせていただいているNWエンジニアです。

表題の通りですが、Telnetmanでコマンドを取得した後、zip logを実行すると「ログがありません。」という画面が表示されます。
READMEの通りに、docker-composeでTelnetmanを起動しています。Windows10環境になります。
解決方法ご教示いただけますと非常に助かります。

**Comment by takahiro-eno** [comment]
ご利用ありがとうございます。
修正しました。
/usr/local/Telnetman2/lib/Telnetman_common.pm
を差し替えて下さい。
新しく作成されたセッションから修正内容が反映されます。

zip ファイルを作成するディレクトリの所有者をapache, パーミッションを775 にしていたのですが、
Docker で動かす場合、なぜか777 にしないとpermission error となるようです。
777 でディレクトリが作成されるようにしました。

**Comment by ghost** [comment]
ご対応ありがとうございます！解決しました。
